version: 0.2

phases:
  build:
    commands:
      - aws deploy push --application-name saishukadaiwork-app --s3-location s3://saishukadaiworks3/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src